<!DOCTYPE html>
<html lang="es">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="rg | born to be keeper" />
    <meta name="keywords" content="rg, rg guantes, guantes de futbol, golero, born to be keeper, guantes, goleros" />
    <meta name="robots" content="index, follow" />

    <title><?php echo 'PROXIMAMENTE - RG - BORN TO BE KEEPER'?></title>
    <base href="<?php echo $this->getSkinUrl()?>" />

    <!-- Bootstrap Core CSS -->
    <link href="<?php echo $this->getSkinUrl()?>css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="<?php echo $this->getSkinUrl()?>css/landing-page.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link rel="icon" href="<?php echo $this->getSkinUrl()?>img/rg-logo.png" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl()?>img/rg-logo.png" type="image/x-icon" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <?php /*
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand topnav" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#services">Services</a>
                    </li>
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    */?>

    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <img src="<?php echo $this->getSkinUrl()?>img/rg-logo.png" alt="RG Born to be Keeper" name="RG BORN TO BE KEEPER"/>
                        <div>
                            <img src="<?php echo $this->getSkinUrl()?>img/rg-gloves.png" alt="ASPRO SNAGA" name="ASPRO SNAGA" style="padding-left: 40px; padding-top: 94px"/>
                        </div>
                        <hr class="intro-divider">
                        <ul id="contact" class="list-inline">
                            <li>
                                <h2>CONTACTANOS: <b>099 14 14 33</b></h2>
                            </li>
                            <li class="break-line">
                                <h2>/</h2>
                            </li>
                            <li style="padding-right: 0">
                                <h2>EMAIL: </h2>
                            </li>
                            <li style="padding: 0">
                                <a href="mailto:consultas@rg.uy" target="_top">
                                    <img style="margin-bottom: 5px" src="<?php echo $this->getSkinUrl()?>img/rg-email.png" alt="RG Born to be Keeper" name="RG BORN TO BE KEEPER"/>
                                </a>
                            </li>
                        </ul>
                        <ul class="list-inline">
                            <li>
                                <a href="https://www.facebook.com/pages/RG-goalkeepers-gloves-Uruguay/237387573111217" target="_blank"><img src="img/rg-fb.png"></a>
                            </li>
                            <li>
                                <a href="https://twitter.com/RG_ArquerosUy" target="_blank"><img src="img/rg-tw.png"></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->
    <!-- jQuery -->
    <script src="<?php echo $this->getSkinUrl()?>js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="<?php echo $this->getSkinUrl()?>js/bootstrap.min.js"></script>
</body>
</html>
