<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php

$_product       = $this->getProduct();
$gripWet        = $_product->getAttributeText('rg_grip_wet');
$gripSunny      = $_product->getAttributeText('rg_grip_sunny');
$abrasionRes    = $_product->getAttributeText('rg_abrasion_res');
?>
<?php if($gripWet): ?>
    <div><label><?php echo $this->__('Grip wet') ?></label> <span><?php echo 'value: ' . $gripWet; ?></span></div>
<?php endif;?>
<?php if($gripSunny): ?>
    <div><label><?php echo $this->__('Grip sunny') ?></label> <span><?php echo 'value: ' . $gripSunny; ?></span></div>
<?php endif;?>
<?php if($abrasionRes): ?>
    <div><label><?php echo $this->__('Abrasion Resistance') ?></label> <span><?php echo 'value: ' . $abrasionRes; ?></span></div>
<?php endif;?>