<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php

$_product       = $this->getProduct();
$gripWet        = $_product->getAttributeText('rg_grip_wet');
$gripSunny      = $_product->getAttributeText('rg_grip_sunny');
$abrasionRes    = $_product->getAttributeText('rg_abrasion_res');
?>
<?php if($gripWet): ?>
    <div class="bkg-prop wet">
        <label><?php echo $this->__('Grip wet') ?></label>
        <span><span class="span-<?php echo $gripWet;?>"></span></span>
    </div>
<?php endif;?>
<?php if($gripSunny): ?>
    <div class="bkg-prop sun">
        <label><?php echo $this->__('Grip sunny') ?></label>
        <span><span class="span-<?php echo $gripSunny;?>"></span></span>
    </div>
<?php endif;?>
<?php if($abrasionRes): ?>
    <div class="bkg-prop adv">
        <label><?php echo $this->__('Abrasion Resistance') ?></label>
        <span><span class="span-<?php echo $abrasionRes;?>"></span></span>
    </div>
<?php endif;?>